### ISSUE TITLE
[Main] Final Year Project Evaluation

### ISSUE THREAD

**Issue by NamalSanjaya** [NamalSanjaya/wave-stack#53]
Evaluation methods
1. Project Presentation
2. Individual Evaluation
3. Project demo

Other Works
1. Research paper writing  @SuhailAhamedlearner 

Important task here is to present the `demo`.

**Comment by NamalSanjaya** [comment]
#### Tasks for final demo
- [x] 1. Test program to show case each functionality (eg : to showcase how `ProviderServiceRequest works)
- [x] 2. Research paper writing
- [x] 3. Preparation for demo day (eg: Need a banner, some sticker to distribute at that day to people that are coming to watch this)
- [x] 4. List down remaining parts in program and make it open source (eg: Remaining functionalities, copyrights header etc)
